/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VandaagRouteImport } from './routes/vandaag'
import { Route as IngredientenRouteImport } from './routes/ingredienten'
import { Route as GerechtenRouteImport } from './routes/gerechten'
import { Route as BoodschappenRouteImport } from './routes/boodschappen'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSuggestMacrosRouteImport } from './routes/api/suggest-macros'

const VandaagRoute = VandaagRouteImport.update({
  id: '/vandaag',
  path: '/vandaag',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientenRoute = IngredientenRouteImport.update({
  id: '/ingredienten',
  path: '/ingredienten',
  getParentRoute: () => rootRouteImport,
} as any)
const GerechtenRoute = GerechtenRouteImport.update({
  id: '/gerechten',
  path: '/gerechten',
  getParentRoute: () => rootRouteImport,
} as any)
const BoodschappenRoute = BoodschappenRouteImport.update({
  id: '/boodschappen',
  path: '/boodschappen',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestMacrosRoute = ApiSuggestMacrosRouteImport.update({
  id: '/api/suggest-macros',
  path: '/api/suggest-macros',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/api/suggest-macros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/api/suggest-macros'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/api/suggest-macros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BoodschappenRoute: typeof BoodschappenRoute
  GerechtenRoute: typeof GerechtenRoute
  IngredientenRoute: typeof IngredientenRoute
  VandaagRoute: typeof VandaagRoute
  ApiSuggestMacrosRoute: typeof ApiSuggestMacrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vandaag': {
      id: '/vandaag'
      path: '/vandaag'
      fullPath: '/vandaag'
      preLoaderRoute: typeof VandaagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredienten': {
      id: '/ingredienten'
      path: '/ingredienten'
      fullPath: '/ingredienten'
      preLoaderRoute: typeof IngredientenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerechten': {
      id: '/gerechten'
      path: '/gerechten'
      fullPath: '/gerechten'
      preLoaderRoute: typeof GerechtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boodschappen': {
      id: '/boodschappen'
      path: '/boodschappen'
      fullPath: '/boodschappen'
      preLoaderRoute: typeof BoodschappenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-macros': {
      id: '/api/suggest-macros'
      path: '/api/suggest-macros'
      fullPath: '/api/suggest-macros'
      preLoaderRoute: typeof ApiSuggestMacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BoodschappenRoute: BoodschappenRoute,
  GerechtenRoute: GerechtenRoute,
  IngredientenRoute: IngredientenRoute,
  VandaagRoute: VandaagRoute,
  ApiSuggestMacrosRoute: ApiSuggestMacrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
