/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VandaagRouteImport } from './routes/vandaag'
import { Route as IngredientenRouteImport } from './routes/ingredienten'
import { Route as GerechtenRouteImport } from './routes/gerechten'
import { Route as BoodschappenRouteImport } from './routes/boodschappen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ApiSuggestMacrosRouteImport } from './routes/api/suggest-macros'
import { Route as AccountVriendenRouteImport } from './routes/account/vrienden'
import { Route as AccountPrivacyRouteImport } from './routes/account/privacy'
import { Route as AccountGegevensRouteImport } from './routes/account/gegevens'
import { Route as AccountDoelRouteImport } from './routes/account/doel'

const VandaagRoute = VandaagRouteImport.update({
  id: '/vandaag',
  path: '/vandaag',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientenRoute = IngredientenRouteImport.update({
  id: '/ingredienten',
  path: '/ingredienten',
  getParentRoute: () => rootRouteImport,
} as any)
const GerechtenRoute = GerechtenRouteImport.update({
  id: '/gerechten',
  path: '/gerechten',
  getParentRoute: () => rootRouteImport,
} as any)
const BoodschappenRoute = BoodschappenRouteImport.update({
  id: '/boodschappen',
  path: '/boodschappen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestMacrosRoute = ApiSuggestMacrosRouteImport.update({
  id: '/api/suggest-macros',
  path: '/api/suggest-macros',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVriendenRoute = AccountVriendenRouteImport.update({
  id: '/account/vrienden',
  path: '/account/vrienden',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/account/privacy',
  path: '/account/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGegevensRoute = AccountGegevensRouteImport.update({
  id: '/account/gegevens',
  path: '/account/gegevens',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDoelRoute = AccountDoelRouteImport.update({
  id: '/account/doel',
  path: '/account/doel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/account/doel': typeof AccountDoelRoute
  '/account/gegevens': typeof AccountGegevensRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/vrienden': typeof AccountVriendenRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/account/doel': typeof AccountDoelRoute
  '/account/gegevens': typeof AccountGegevensRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/vrienden': typeof AccountVriendenRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boodschappen': typeof BoodschappenRoute
  '/gerechten': typeof GerechtenRoute
  '/ingredienten': typeof IngredientenRoute
  '/vandaag': typeof VandaagRoute
  '/account/doel': typeof AccountDoelRoute
  '/account/gegevens': typeof AccountGegevensRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/vrienden': typeof AccountVriendenRoute
  '/api/suggest-macros': typeof ApiSuggestMacrosRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/account/doel'
    | '/account/gegevens'
    | '/account/privacy'
    | '/account/vrienden'
    | '/api/suggest-macros'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/account/doel'
    | '/account/gegevens'
    | '/account/privacy'
    | '/account/vrienden'
    | '/api/suggest-macros'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/boodschappen'
    | '/gerechten'
    | '/ingredienten'
    | '/vandaag'
    | '/account/doel'
    | '/account/gegevens'
    | '/account/privacy'
    | '/account/vrienden'
    | '/api/suggest-macros'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoodschappenRoute: typeof BoodschappenRoute
  GerechtenRoute: typeof GerechtenRoute
  IngredientenRoute: typeof IngredientenRoute
  VandaagRoute: typeof VandaagRoute
  AccountDoelRoute: typeof AccountDoelRoute
  AccountGegevensRoute: typeof AccountGegevensRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AccountVriendenRoute: typeof AccountVriendenRoute
  ApiSuggestMacrosRoute: typeof ApiSuggestMacrosRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vandaag': {
      id: '/vandaag'
      path: '/vandaag'
      fullPath: '/vandaag'
      preLoaderRoute: typeof VandaagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredienten': {
      id: '/ingredienten'
      path: '/ingredienten'
      fullPath: '/ingredienten'
      preLoaderRoute: typeof IngredientenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerechten': {
      id: '/gerechten'
      path: '/gerechten'
      fullPath: '/gerechten'
      preLoaderRoute: typeof GerechtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boodschappen': {
      id: '/boodschappen'
      path: '/boodschappen'
      fullPath: '/boodschappen'
      preLoaderRoute: typeof BoodschappenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-macros': {
      id: '/api/suggest-macros'
      path: '/api/suggest-macros'
      fullPath: '/api/suggest-macros'
      preLoaderRoute: typeof ApiSuggestMacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/vrienden': {
      id: '/account/vrienden'
      path: '/account/vrienden'
      fullPath: '/account/vrienden'
      preLoaderRoute: typeof AccountVriendenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/account/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/gegevens': {
      id: '/account/gegevens'
      path: '/account/gegevens'
      fullPath: '/account/gegevens'
      preLoaderRoute: typeof AccountGegevensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/doel': {
      id: '/account/doel'
      path: '/account/doel'
      fullPath: '/account/doel'
      preLoaderRoute: typeof AccountDoelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoodschappenRoute: BoodschappenRoute,
  GerechtenRoute: GerechtenRoute,
  IngredientenRoute: IngredientenRoute,
  VandaagRoute: VandaagRoute,
  AccountDoelRoute: AccountDoelRoute,
  AccountGegevensRoute: AccountGegevensRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AccountVriendenRoute: AccountVriendenRoute,
  ApiSuggestMacrosRoute: ApiSuggestMacrosRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
